# Generated by Django 3.0.6 on 2020-07-24 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Post_In_Team', models.TextField(choices=[('Captain', 'Captain'), ('Captain and Driver', 'Captain and Driver'), ('Vice-Captain', 'Vice-Captain'), ('Vice-Captain and Driver', 'Vice-Captain and Driver'), ('Project Manager', 'Project Manager'), ('Project Manager and Driver', 'Project Manager and Driver'), ('Driver', 'Driver'), ('Codriver', 'Codriver'), ('Tier-1 Member', 'Tier-1 Member'), ('Tier-2 Member', 'Tier-2 Member'), ('None', 'None')], default='None')),
                ('Subsystem', models.TextField(choices=[('Transmission', 'Transmission'), ('Suspension', 'Suspension'), ('Steering', 'Steering'), ('Brakes', 'Brakes'), ('Rollcage', 'Rollcage'), ('Project Management', 'Project Management'), ('None', 'None')], default='None')),
                ('Post_In_Subsystem', models.TextField(choices=[('Head', 'Head'), ('Senior Member', 'Senior Member'), ('Member', 'Member'), ('None', 'None')], default='None')),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
